kind: pipeline
name: default

steps:
- name: version
  image: python
  commands:
  - python3 --version
 
- name: pip install
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
